name: 'leetcode-solved-problem-tracker'
description: 'leetcode-solved-problem-tracker'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  username:
    description: 'username'
    required: true
    default: ''
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
runs:
  using: 'node12'
  main: 'index.js'
